### ISSUE TITLE
Format BAM Repo with Prettier

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/iobio-components#14]
Format BAM repo with Prettier so that the code is more clean and easer to read and interpret when collaborating with the IOBIO team

**Comment by demariadaniel** [comment]
Iobio team has elected to create a new set of Bam components, so updating the previous Bam repo will not be needed
Prettier config has been adapted for use with Iobio-Components as part of https://github.com/overture-stack/iobio-components/issues/6
