### ISSUE TITLE
Setup & Configure IOBIO Repo

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/iobio-components#6]
Setup and configure initial IOBIO repo

- [ ] Determine if we should fork the original IOBIO project
- [ ] Determine if we need to establish sub-modules (a way of having our own version of BAM while still being able to get updates from IOBIO)
- [ ] Determine how both repos will stay in sync

## Expected Outcomes ##

- [ ] Wiki page documenting the decisions for the above

**Comment by demariadaniel** [comment]
Repo Setup Wiki analysis here: https://wiki.oicr.on.ca/display/OV/Iobio+Components+Setup+Analysis
