### ISSUE TITLE
Create a BAM NPM Package

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/iobio-components#7]
Create a BAM NPM package from the original IOBIO code that is to be used by/for SoftEng and its purposes

## EXPECTED OUTCOMES ##

- [ ] A published BAM NPM package on the SoftEng repo that can be imported into Overture Stage

**Comment by demariadaniel** [comment]
Published here:
https://www.npmjs.com/package/@overture-stack/iobio-components

Able to install in Stage
